builds:
  - binary: avxctl
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: avxctl
    homepage: https://github.com/aajolly/avxctl
    tap:
      owner: aajolly
      name: homebrew-jollyprojects
    commit_author:
      name: aajolly
      email: aashish.jolly@gmail.com
checksum:
  name_template: 'checksums.txt'
