# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: avxctl
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: avxctl
    homepage: https://github.com/aajolly/avx-single-region-aws
    repository:
      owner: aajolly
      name: homebrew-jollyprojects
    commit_author:
      name: aajolly
      email: aashish.jolly@gmail.com
checksum:
  name_template: 'checksums.txt'
